### ISSUE TITLE
New tag / release

### ISSUE THREAD

**Issue by Zizaco** [logentries/logentries-monolog-handler#8]
@schickling @logentries-community @logentries @StephenHynes7
Having to include this package with `dev-master` or (in our case) `dev-master#f3391fb68a90b4a59c49b533056660d17ea318a1` is terrible. The 2498cda7f2762aee2d9edb60f86fd70799cabc9e _(Fix bug with stream timeout)_ has been around for a while now. What do you guys think of tagging a newer commit with `v2.0.1` or something?

**Comment by rplansky** [comment]
:+1:

**Comment by fernandofleury** [comment]
Ran into this issue as well. What can we do in order to make this happen?

**Comment by gearoidof** [comment]
Released as v2.1, sorry for the delay

**Comment by Zizaco** [comment]
Thanks!
